// Arrays to store the sequence generated by the game and the sequence clicked by the user
let gameSeq = [];
let userSeq = [];

// Available button colors
let btn = ["yellow","red","purple","green"];

// Game state variables
let started = false;
let level = 0;

let h2 = document.querySelector("h2");       // Select the <h2> element to display the current level or game over message
let btncontainer = document.querySelector(".btn-container");

// Start on keypress (desktop)
document.addEventListener("keypress", startGame);

// Start on  touch (mobile-friendly)
document.addEventListener("touchstart", startGame);

// Start the game on key press or first tap/click
function startGame() {
    if (!started) {
        btncontainer.classList.remove("display");
        started = true;
        levelUp();
    }
}


// Function to go to the next level
function levelUp() {
    userSeq = [];                                                 // Reset user sequence for the new level
    level++;                                                      // Increment the level count
    h2.innerText = `level ${level}`;                                // Display the current level

    let randIdx = Math.floor(Math.random() * 4);                       // Generate random index between 0 and 3
    let randColor = btn[randIdx];                                     // Pick a random color from the 'btn' array
    let randBtn = document.querySelector(`.${randColor}`);             // Select the button with the corresponding class
    gameSeq.push(randColor);                                            // Add color to game sequence
    console.log(gameSeq);                                                // print game sequence

    gameflash(randBtn);                                           // Flash the randomly selected button
}

// Function to visually flash the game's button
function gameflash(btn) {
    btn.classList.add("flash");                              // Add the "flash" class to trigger CSS style

    setTimeout(function () {
        btn.classList.remove("flash");                           // Remove the "flash" class after 250ms
    }, 250);
}


// Select all buttons and add click event listeners
let allbtns = document.querySelectorAll(".btn");
for (button of allbtns){                                       // Loop through each button and attach a click event listener
    button.addEventListener("click", btnpress);                // Call btnpress on click
}

// Function triggered when a user clicks a button
function btnpress(){                    
    let btn = this;                         // 'this' refers to the button that was clicked
    userflash(btn);                         // Trigger the flash effect on the clicked button

    let userColor = btn.getAttribute("id");                          // Get color (id) of the clicked button
    userSeq.push(userColor);                                          // Add to user sequence

    checkans(userSeq.length-1);                                        // Check the last user input
}

// Function to flash the button on user click
function userflash(btn) {
    btn.classList.add("userflash");                                // Add the "userflash" class to trigger CSS style

    setTimeout(function () {
        btn.classList.remove("userflash");                           // Remove the "userflash" class after 250ms
    }, 250);
}

// Function to check the user's answer against the game sequence
function checkans(idx){
    if(userSeq[idx] === gameSeq[idx]){                                 // Check if current input is correct
        if(userSeq.length == gameSeq.length){                           // If full sequence is correct
            setTimeout(levelUp,1000);                                   // Proceed to next level after a delay
        }
    }else{                                                            // If user made a mistake
        h2.innerHTML = `Game Over! Your score was <b>${level}</b> <br> press any key to start again.`;
        document.querySelector("body").style.backgroundColor = "red";                                     // Flash red background
        setTimeout(function(){
            document.querySelector("body").style.backgroundColor = "white";                                // Reset background
        },150); 
        reset();                                                                    // Reset the game
    }

}

// Function to reset the game state
function reset(){                          
    started = false;
    gameSeq = [];
    userSeq = [];
    level = 0;
    btncontainer.classList.add("display");
}
